# Generated by Django 5.1 on 2024-08-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_account_user_account_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
