# Generated by Django 5.1 on 2024-09-01 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='valid_from',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='valid_until',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='cashback_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='entity_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='applicable_to',
            field=models.CharField(help_text="Applicable to products like 'Credit Card', 'Savings Account', 'Loan', etc.", max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('cashback', 'Cashback'), ('interest_discount', 'Interest Rate Discount'), ('fee_waiver', 'Fee Waiver'), ('reward_points', 'Reward Points'), ('signup_bonus', 'Signup Bonus'), ('transaction_bonus', 'Transaction Bonus')], max_length=20),
        ),
    ]
