# Generated by Django 5.1 on 2024-09-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0002_rename_valid_from_offer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Value of the offer (e.g., cashback amount, interest discount rate).', max_digits=10),
        ),
    ]
