# Generated by Django 5.1 on 2024-09-02 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillPayment', '0001_initial'),
        ('Customer', '0002_rename_name_customer_uname_remove_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpayment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='billpayment',
            name='due_date',
        ),
        migrations.AddField(
            model_name='billpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('bill_type', models.CharField(choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Internet', 'Internet'), ('Phone', 'Phone'), ('Other', 'Other')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='Customer.customer')),
            ],
        ),
        migrations.AddField(
            model_name='billpayment',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billpayments', to='BillPayment.bill'),
        ),
    ]
