# Generated by Django 5.1 on 2024-08-18 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('credit', 'Credit Card'), ('debit', 'Debit Card')], max_length=10)),
                ('cardholder_name', models.CharField(max_length=255)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('bank_name', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('pin', models.CharField(max_length=4)),
                ('billing_address', models.TextField()),
                ('daily_transaction_limit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='active', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Customer.customer')),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Account.account')),
            ],
        ),
    ]
