# Generated by Django 5.1 on 2024-08-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0002_card_created_at_card_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='billing_address',
        ),
    ]
