# Generated by Django 5.1 on 2024-09-01 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_rename_name_customer_uname_remove_customer_password'),
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='interest_rate',
            new_name='investment_rate',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='return_on_investment',
            new_name='total_profit',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='maturity_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='investment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Investments', to='Customer.customer'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('fixed_deposit', 'Fixed Deposit'), ('mutual_fund', 'Mutual Fund'), ('stock', 'Stock'), ('bond', 'Bond'), ('real_estate', 'Real Estate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='start_date',
            field=models.DateField(),
        ),
    ]
