# Generated by Django 5.1 on 2024-08-22 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_user_address_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user_email',
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(default='eit', on_delete=django.db.models.deletion.CASCADE, to='User.user'),
            preserve_default=False,
        ),
    ]
